#!/bin/bash
# SML CSS Build Script - Concatenates all CSS into single file

OUTPUT="data/css/main-bundle.css"
INPUT_DIR="data/css"

echo "Building SML CSS bundle..."

# Create bundle with header
cat > "$OUTPUT" << 'EOF'
/*=============== SML Web Interface v2.1 - Consolidated CSS Bundle ===============*/
/* Auto-generated by build-css.sh - DO NOT EDIT MANUALLY */
/* Generated: $(date) */

/* === Base === */
EOF

# Concatenate files in correct order
echo "Adding base CSS..."
cat "$INPUT_DIR/base/reset.css" >> "$OUTPUT"
echo "" >> "$OUTPUT"
cat "$INPUT_DIR/base/variables.css" >> "$OUTPUT"
echo "" >> "$OUTPUT"
cat "$INPUT_DIR/base/typography.css" >> "$OUTPUT"
echo "" >> "$OUTPUT"

cat >> "$OUTPUT" << 'EOF'

/* === Layout === */
EOF

cat "$INPUT_DIR/layout/grid.css" >> "$OUTPUT"
echo "" >> "$OUTPUT"
cat "$INPUT_DIR/layout/responsive-nav.css" >> "$OUTPUT"
echo "" >> "$OUTPUT"
cat "$INPUT_DIR/layout/header.css" >> "$OUTPUT"
echo "" >> "$OUTPUT"
cat "$INPUT_DIR/layout/wled-theme.css" >> "$OUTPUT"
echo "" >> "$OUTPUT"

cat >> "$OUTPUT" << 'EOF'

/* === Components === */
EOF

cat "$INPUT_DIR/components/buttons.css" >> "$OUTPUT"
echo "" >> "$OUTPUT"
cat "$INPUT_DIR/components/forms.css" >> "$OUTPUT"
echo "" >> "$OUTPUT"
cat "$INPUT_DIR/components/battery.css" >> "$OUTPUT"
echo "" >> "$OUTPUT"
cat "$INPUT_DIR/components/player.css" >> "$OUTPUT"
echo "" >> "$OUTPUT"
cat "$INPUT_DIR/components/thermometer.css" >> "$OUTPUT"
echo "" >> "$OUTPUT"

cat >> "$OUTPUT" << 'EOF'

/* === Themes === */
EOF

cat "$INPUT_DIR/themes/sml-brand.css" >> "$OUTPUT"
echo "" >> "$OUTPUT"

cat >> "$OUTPUT" << 'EOF'

/* === Pages === */
EOF

cat "$INPUT_DIR/pages/peek-preview.css" >> "$OUTPUT"
echo "" >> "$OUTPUT"
cat "$INPUT_DIR/pages/effects-config.css" >> "$OUTPUT"
echo "" >> "$OUTPUT"
cat "$INPUT_DIR/pages/config-tab.css" >> "$OUTPUT"

# Get size
SIZE=$(du -h "$OUTPUT" | cut -f1)
LINES=$(wc -l < "$OUTPUT")

echo ""
echo "✅ CSS bundle created: $OUTPUT"
echo "   Size: $SIZE"
echo "   Lines: $LINES"
echo ""
echo "To use in production, update index.html:"
echo "  Replace: <link rel=\"stylesheet\" href=\"css/main.css\">"
echo "  With:    <link rel=\"stylesheet\" href=\"css/main-bundle.css\">"
